@startuml
object StartMenu
object Games
object Snake
object BrickBreaker
object PacMan
object BallDrop
object Difficulties
object StartGame
object viewHighScore

StartMenu <--> Games

Games <|-- Snake
Games <|-- BrickBreaker
Games <|-- PacMan
Games <|-- BallDrop

BallDrop o-- Difficulties
Snake o-- Difficulties
BrickBreaker o-- Difficulties
PacMan o-- Difficulties

BallDrop o-- viewHighScore
Snake o-- viewHighScore
BrickBreaker o-- viewHighScore
PacMan o-- viewHighScore

Difficulties <-- StartGame
viewHighScore <-- StartGame

StartMenu <-- StartGame



@enduml