@startuml
object StartMenu
object Games
object Snake
object BrickBreaker
object PacMan
object BallDrop
object Difficulties
object StartGame
object HighScore
object viewHighScore

StartMenu <.. Games

Games o-- Snake
Games o-- BrickBreaker
Games o-- PacMan
Games o-- BallDrop

BallDrop o-- Difficulties
Snake o-- Difficulties
BrickBreaker o-- Difficulties
PacMan o-- Difficulties

BallDrop <.. viewHighScore
Snake <.. viewHighScore
BrickBreaker <.. viewHighScore
PacMan <.. viewHighScore

Difficulties <-- StartGame

StartGame <-- HighScore

StartMenu <-- HighScore



@enduml